language: php

php:
  - 5.6

install:
  - composer install
  - composer require satooshi/php-coveralls '~1.0'
  - nvm install 6
  - nvm use 6
  - npm install
  - npm install codecov

script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml
  - ./node_modules/bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly ./test/js -- -R spec

# Submit generated coverage report to Codecov servers
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF php
  - ./node_modules/bin/codecov
 